### ISSUE TITLE
In Chrome browser, can't hang up as caller

### ISSUE THREAD

**Issue by gnusupport** [mehrvarz/webcall#19] opened 2022-10-07 12:42 UTC
I see only red light, I can see in Chrome browser the button "Hang up" but can't hang up. When clicking the button I can hear the busy signal, but can't hang up.

**Comment by mehrvarz** [comment] 2022-10-07 18:53
Chrome browser on what type of device? iphone?

**Comment by gnusupport** [comment] 2022-10-07 23:13
Android

**Comment by mehrvarz** [comment] 2022-10-08 05:50
Some 3rd party Chrome-based browsers on Android do not fully support WebRTC. It is the same issue that exists with some 3rd party System WebViews. I try to describe the problem [here](https://timur.mobi/webcall/android/#webview).

I just now checked the Hang-Up button with G Chromium as well as with Kiwi-Browser with no issues. I am not able to reproduce any issue.

Are you sure your browsers supports WebRTC? Please give these WebRTC samples a try: https://webrtc.github.io/samples/ in particular the [Basic peer connection demo in a single tab](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) which also has a Hang-up feature.

**Comment by mehrvarz** [comment] 2022-12-14 15:13
I am closing this now. If the issue persists, please re-open.

**Closed by mehrvarz** 2022-12-14 15:13 UTC
